### ISSUE TITLE
Create layout of the web app

### ISSUE THREAD

**Issue by fabricio-garcia** [fabricio-garcia/todo-js#1]
The Web App structure should contain the next features:

- [ ]  Create the layout design
    - [x]  The app is divided in separate views for different purposes
    - [ ]  Create a view to welcome the user
        - [ ]  In the welcome view you can write your name
    - [x]  Create a main view
        - [x]  There's a navbar in the mai view
        - [x]  There's a list of projects in the main view
        - [x]  Each project in the main view has a title, a description, few items and a delete and edit buttons
        - [x]  There's an "add new" button in the main view
    - [x]  Create an project view to starage and view individual projects
        - [x]  There's a title in the auxiliary view
        - [x]  You can add todos in the auxiliary views
        - [x]  There's a button to mark one to do as completed
        - [x]  There's a button to mark one to do as completed
    - [x]  Create a view to see an individual to do
        - [x]  In the individual to do view yu can edit and erase the to do

**Comment by Israel-Laguan** [comment]
# Requirements from [The Odin Project](https://www.theodinproject.com/courses/javascript/lessons/todo-list)

> The look of the User Interface is up to you, but it should be able to do the following:

- [ ] view all projects
- [ ]   view all todos in each project (probably just the title and duedate.. perhaps changing color for different priorities)
- [ ] expand a single todo to see/edit it’s details
- [ ] delete a todo
